In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split, KFold, cross_val_score, cross_val_predict

In [2]:
np.random.seed(42)

In [3]:
data = pd.read_csv("./train.csv")
X = data.drop(columns=["Id", "y"])
y = data["y"]

In [4]:
linear = lambda x : x
quadratic = lambda x : x**2
exponential = lambda x : np.exp(x)
cosine = lambda x : np.cos(x)
constant = lambda x : np.ones(x.shape)

In [5]:
features = {}

for phi in range(0,4):
    for i in range(1, 6):
        if phi == 0:
            features[f"phi_{i+phi*5}"] = linear(X.iloc[:, i-1].values)
        if phi == 1:
            features[f"phi_{i+phi*5}"] = quadratic(X.iloc[:, i-1].values)
        if phi == 2:
            features[f"phi_{i+phi*5}"] = exponential(X.iloc[:, i-1].values)
        if phi == 3:
            features[f"phi_{i+phi*5}"] = cosine(X.iloc[:, i-1].values)
            
features[f"phi_{21}"] = constant(X.iloc[:, 0].values)

In [6]:
X = pd.DataFrame(features)
# X

In [7]:
reg = LinearRegression(fit_intercept=False)

In [8]:
from sklearn.feature_selection import RFECV

In [9]:
selector = RFECV(reg, step=1, cv=5)
selector = selector.fit(X, y)
selector.support_

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True])

In [10]:
selector.ranking_

array([18, 16,  7, 14,  5, 10, 20,  2, 12,  4, 19, 17,  8, 13,  6,  9, 15,
        1, 11,  3,  1])

In [11]:
X.iloc[:, selector.support_]

phi_18  phi_21
0    0.995953     1.0
1    0.996802     1.0
2    0.997551     1.0
3    0.999950     1.0
4    0.996802     1.0
..        ...     ...
695  0.999200     1.0
696  0.999800     1.0
697  0.999950     1.0
698  0.998750     1.0
699  0.998201     1.0

[700 rows x 2 columns]

In [12]:
reg.fit(X.iloc[:, selector.support_], y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)

In [13]:
reg.coef_

array([ 20.39786684, -19.28758959])

In [14]:
# np.savetxt("submission_1b.csv", reg.coef_)